### ISSUE TITLE
Not working in Germany

### ISSUE THREAD

**Issue by UnixCro** [anthropomorphic/auto_survey#1]
Us site is www.mcdonalds.de/deinfeedback with a code example "aac0-du0y-lqyu"

Thank you

**Comment by mfdorst** [comment]
@UnixCro yeah this has long since stopped working. It's highly dependent on the exact code of the site, which will obviously change over time.

**Comment by mfdorst** [comment]
I updated the readme to reflect that this is long since outdated and not working.

**Comment by UnixCro** [comment]
If you can't update it to the current status, nothing changes on the website that often.  The benefit is much greater than the effort.  It could save so many people time by doing these things themselves.  They would advance the group of people and they might reward themselves for their actions.  Best regards

**Comment by mfdorst** [comment]
Even minor behind the scenes changes on the site break things, so this would have to be updated constantly to keep it working. Since I don't use it anymore I'm just not interested. If you'd like to take over the upkeep, please feel free.
